# Generated by Django 4.2.4 on 2023-10-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0003_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ubicacion", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("foto", models.ImageField(upload_to="inmuebles/")),
            ],
        ),
    ]
