# Generated by Django 4.2.4 on 2023-10-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0007_comentario_inmueble_comentarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="inmueble",
            name="ciudad",
            field=models.CharField(default="Desconocida", max_length=100),
        ),
        migrations.AddField(
            model_name="inmueble",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
