# Generated by Django 4.2.4 on 2023-10-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0009_inmueble_vendedor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inmueble",
            name="vendedor",
        ),
    ]
