# Generated by Django 4.2.4 on 2023-10-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0010_remove_inmueble_vendedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="tipo_de_usuario",
            field=models.CharField(
                choices=[("comprador", "Comprador"), ("vendedor", "Vendedor")],
                max_length=20,
            ),
        ),
    ]
